"""Merge refs/chNN.bib into refs/all.bib with one entry per key.

Chapters are drafted separately and often cite the same work under the same
key, which bibtex rejects as a repeated entry in a whole-book build. This keeps
the first entry for each key (in main.tex chapter order) and reports every key
whose duplicate entries differ in content, so a disagreement between chapters
is fixed by hand rather than hidden.

Run from the repository root: python tools/merge_bib.py
Exit status 1 if any duplicate key has conflicting content.
"""
import re
import sys


def entries(text):
    """Yield (key, raw_entry) for each @type{key, ...} with balanced braces."""
    i = 0
    while True:
        m = re.compile(r"@(\w+)\s*\{\s*([^,\s]+)\s*,").search(text, i)
        if not m:
            return
        if m.group(1).lower() in ("comment", "preamble", "string"):
            i = m.end()
            continue
        depth, j = 0, m.start() + text[m.start():].index("{")
        for k in range(j, len(text)):
            depth += {"{": 1, "}": -1}.get(text[k], 0)
            if depth == 0:
                yield m.group(2), text[m.start():k + 1]
                i = k + 1
                break
        else:
            return


def normalise(raw):
    return re.sub(r"\s+", " ", raw.lower()).replace("{", "").replace("}", "")


def doi(raw):
    m = re.search(r"\bdoi\s*=\s*[{\"]([^}\"]+)", raw, re.I)
    return m.group(1).strip().lower() if m else None


def same_work(a, b):
    """Identical text, or the same DOI (publisher spelled differently, etc.)."""
    if normalise(a) == normalise(b):
        return True
    return doi(a) is not None and doi(a) == doi(b)


main = open("main.tex", encoding="utf-8").read()
order = re.findall(r"refs/(ch\d\d)", main)
kept, source, conflicts = {}, {}, []
for ch in order:
    try:
        text = open("refs/%s.bib" % ch, encoding="utf-8").read()
    except FileNotFoundError:
        continue
    for key, raw in entries(text):
        if key not in kept:
            kept[key], source[key] = raw, ch
        elif not same_work(raw, kept[key]):
            conflicts.append((key, source[key], ch))

with open("refs/all.bib", "w", encoding="utf-8", newline="\n") as out:
    out.write("% Generated by tools/merge_bib.py from refs/chNN.bib. Do not edit by hand.\n\n")
    for key in sorted(kept, key=str.lower):
        out.write(kept[key].strip() + "\n\n")

print("%d unique entries from %d chapter files" % (len(kept), len(order)))
for key, first, other in conflicts:
    print("CONFLICT %s: %s differs from %s" % (key, other, first))
sys.exit(1 if conflicts else 0)
